openapi: 3.2.0
info:
  title: Salesflare Email Data Sources API
  version: 1.0.0
  description: '# Introduction


    ## Getting Started


    The Salesflare API allows you to access and build your own applications or integrations that interact with Salesflare.'
  contact:
    email: support@salesflare.com
  x-logo:
    url: https://lib.salesflare.com/api_docs/sf-logo-inverted.svg
    backgroundColor: '#0f1528'
    altText: Salesflare logo
servers:
- url: https://api.salesflare.com
tags:
- name: Email Data Sources
paths:
  /datasources/email:
    get:
      summary: List email data sources
      operationId: getDatasourcesEmail
      parameters:
      - description: Team data sources will only be included when the session user is an admin.
        name: includeTeamDataSources
        in: query
        schema:
          type: boolean
          default: false
      tags:
      - Email Data Sources
      responses:
        '200':
          description: Successful
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    aliases:
                      type: array
                      items:
                        type: object
                        properties:
                          email:
                            type: string
                            x-format:
                              email:
                                ignoreLength: true
                                tlds:
                                  allow: false
                                minDomainSegments: 1
                            x-convert:
                              case: lower
                          display_name:
                            type: string
                        required:
                        - email
                        - display_name
                    email:
                      type: string
                    type:
                      type: string
                      enum:
                      - google
                      - office365
                      - nylas
                      - imap
                    name:
                      type: string
                    team:
                      type: number
                    user:
                      type: number
                    email_signature:
                      type: string
                    add_signature_to_campaign:
                      type: boolean
                    add_signature_to_replies:
                      type: boolean
                    max_emails_day:
                      type: number
                    max_emails_hour:
                      type: number
                    primary:
                      type: boolean
                    host:
                      type: string
                    port:
                      type: number
                    smtp_host:
                      type: string
                    smtp_port:
                      type: number
                    store_sent_emails:
                      type: boolean
                    status:
                      type: string
                      enum:
                      - OK
                      - RECONNECT
                      - ERROR
                    sync_status:
                      type: string
                      enum:
                      - initial
                      - cache
                      - sync
                      - enrich
                      - done
                  required:
                  - id
                  - aliases
                  - email
                  - type
                  - name
                  - team
                  - user
                  - add_signature_to_campaign
                  - add_signature_to_replies
                  - max_emails_day
                  - max_emails_hour
                  - primary
                  - status
                  - sync_status
  /datasources/email/{id}:
    put:
      summary: Update an email data source
      operationId: putDatasourcesEmailId
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email_signature:
                  type: string
                add_signature_to_campaign:
                  type: boolean
                add_signature_to_replies:
                  type: boolean
                max_emails_day:
                  type: number
                  minimum: 0
                  maximum: 2000
                max_emails_hour:
                  type: number
                  minimum: 0
                  maximum: 200
      tags:
      - Email Data Sources
      responses:
        default:
          description: Successful
          content:
            '*/*':
              schema:
                type: string
x-tagGroups:
- name: General
  tags:
  - Tasks
  - Accounts
  - Contacts
  - Opportunities
  - Workflows
  - Insights
- name: Interactions
  tags:
  - Calls
  - Meetings
  - Internal Notes
- name: User Management
  tags:
  - Users
  - Groups
- name: Configuration
  tags:
  - Regional Settings
  - Pipelines
  - Custom Fields
  - Email Data Sources
  - Tags
  - Filter Fields
  - Persons
